### ISSUE TITLE
docset无名字，关键字

### ISSUE THREAD

**Issue by xoit** [xuelangZF/html2Dash#1]
在windows使用这个脚本，copy的动作我手动做了，命令注释掉，这样出来的docset可以被打开，但是不知道为什么没有名字，只有icon图标？

可以加关键字搜索么？

**Comment by selfboot** [comment]
这里生成 docset 参考了官方给的 os x下生成的步骤，没了解过 win 下的dash是怎么一回事

搜索的话，dash 自带的搜索，可以搜索出关键字的吧
