### ISSUE TITLE
有问题咨询

### ISSUE THREAD

**Issue by Tairraos** [xuelangZF/html2Dash#2]
纯净osx缺少BS4，应该在readme里提示用户如何安装bs4

**Comment by Tairraos** [comment]
通过如下命令安装了bs4
wget https://pypi.python.org/packages/source/p/pip/pip-1.5.6.tar.gz
tar zxvf pip-1.5.6.tar.gz
cd pip-1.5.6
sudo python setup.py install
sudo pip install beautifulsoup4

---

使用wget镜象了react, http://reactjs.cn/react/docs
$wget -r -p -k -np http://reactjs.cn/react/docs/
--2016-07-30 09:47:28--  http://reactjs.cn/react/docs/
Resolving reactjs.cn... 115.29.248.36
Connecting to reactjs.cn|115.29.248.36|:80... connected.
HTTP request sent, awaiting response... 200 OK
....................
.................

---

使用下面命令行build：
$./html2dash.py -n React中文 -i reactjs.cn/react/react.png reactjs.cn/react/docs
Docset Folder already exist!
Copy the HTML Documentation!
Create the SQLite Index
/Library/Python/2.7/site-packages/bs4/**init**.py:181: UserWarning: No parser was explicitly specified, so I'm using the best available HTML parser for this system ("html.parser"). This usually isn't a problem, but if you run this code on another system, or in a different virtual environment, it may use a different parser and behave differently.

The code that caused this warning is on line 167 of the file ./html2dash.py. To get rid of this warning, change code that looks like this:

 BeautifulSoup([your markup])

to this:

 BeautifulSoup([your markup], "html.parser")

  markup_type=markup_type))
Create the Info.plist File
Create the Icon for the Docset!
Generate Docset Successfully!

---

build成功了，大小3.8M
但是导入dash后无法阅读, 没有内容，搜索也找不到内容
![image](https://cloud.githubusercontent.com/assets/185069/17267603/0465ca7a-5640-11e6-8c95-8021f3d2d29f.png)

**Comment by Tairraos** [comment]
我查看了所有镜象下来的html文件，发现有很多绝对路径的链接。index.html直接是一个redirect指令。
我把index修改成redirect目标一致的html文件，并把所有的绝对路径都改成了相对路径后。build提示依然一样。但是build出来的docset有Search目录，也能被Search到内容。

但是点击内容，右侧什么都不会显示。如图

![image](https://cloud.githubusercontent.com/assets/185069/17267877/fbf3d27a-5648-11e6-9431-b4fce9dd409e.png)

**Comment by selfboot** [comment]
把 30 行的 

```
soup = BeautifulSoup(index_page)
```

改为

```
soup = BeautifulSoup(index_page, "html.parser")
```

试试

**Comment by Tairraos** [comment]
这样做，build不会有警告提示了，但是build出来的文件仍然不能被打开。
$./html2dash.py -n React中文 -i reactjs.cn/react/react.png reactjs.cn/react/docs
Docset Folder already exist!
Copy the HTML Documentation!
Create the SQLite Index
Create the Info.plist File
Create the Icon for the Docset!
Generate Docset Successfully!

---

看图，Sections里任意一项点击后，右侧不会显示内容。在搜索窗能搜索到内容，但是点击搜索结果也不会显示内容。
![image](https://cloud.githubusercontent.com/assets/185069/17273787/432c2d0c-56f5-11e6-82b4-11c8185c7b8d.png)

---

被压缩的react镜象包上传不上来。我传到百度云了。如果需要，下载下来测试下。压缩后608k
链接: http://pan.baidu.com/s/1cfxw54 密码: rmfx

谢谢，辛苦了。

**Comment by Tairraos** [comment]
被压缩包附上。文件名修改成 reactcn.tgz 后解包。github不能上传tgz。
辛苦了，谢谢

**Comment by selfboot** [comment]
@Tairraos 试了下，确实不行，不知道问题在哪里。

**Comment by Tairraos** [comment]
我看了下结果，有几个问题。
1 sections里的内容是根据index.html里的所有的《a》生成的，index里会有很多《a》不合理。 建议扫描所有的链接，根据每个page的《title》来生成
2 也可以根据《title》来生成guide，根据每个页面里的《h1》《h2》《h3》生成section
3 如果index.html引用了比它文件夹位置高的文件，不会被打进包里。

另外，前面包的问题是因为文件名里有中文造成的。我手动把包内容编辑后，docset访问无误了。

**Comment by selfboot** [comment]
@Tairraos 你可以改一下，pull 给我。我最近没时间搞这个了。

**Comment by Tairraos** [comment]
http://download.csdn.net/detail/xiaole_tao/9592441  我py不会呀。罪过。。

**Comment by selfboot** [comment]
@Tairraos 那就先这样吧，凑合着能用
